# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-TimePiece
version:      0.01
version_from: lib/Class/DBI/Plugin/TimePiece.pm
installdirs:  site
requires:
    Carp:                          0
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
